# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PartiiService_pb2 as PartiiService__pb2


class TranscriptionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWordID = channel.unary_unary(
                '/partii.Transcription/GetWordID',
                request_serializer=PartiiService__pb2.Word.SerializeToString,
                response_deserializer=PartiiService__pb2.WordResult.FromString,
                )
        self.WakeWord = channel.stream_stream(
                '/partii.Transcription/WakeWord',
                request_serializer=PartiiService__pb2.AudioData.SerializeToString,
                response_deserializer=PartiiService__pb2.WakeWordResult.FromString,
                )
        self.WakeWordAndLiveTranscribe = channel.stream_stream(
                '/partii.Transcription/WakeWordAndLiveTranscribe',
                request_serializer=PartiiService__pb2.AudioData.SerializeToString,
                response_deserializer=PartiiService__pb2.WakeWordAndTranscriptionResult.FromString,
                )
        self.SingleTranscribe = channel.stream_stream(
                '/partii.Transcription/SingleTranscribe',
                request_serializer=PartiiService__pb2.AudioData.SerializeToString,
                response_deserializer=PartiiService__pb2.TranscriptionResult.FromString,
                )
        self.LiveTranscribe = channel.stream_stream(
                '/partii.Transcription/LiveTranscribe',
                request_serializer=PartiiService__pb2.AudioData.SerializeToString,
                response_deserializer=PartiiService__pb2.TranscriptionResult.FromString,
                )
        self.FileTranscribe = channel.stream_stream(
                '/partii.Transcription/FileTranscribe',
                request_serializer=PartiiService__pb2.AudioData.SerializeToString,
                response_deserializer=PartiiService__pb2.TranscriptionResult.FromString,
                )
        self.LiveEmotion = channel.stream_stream(
                '/partii.Transcription/LiveEmotion',
                request_serializer=PartiiService__pb2.AudioData.SerializeToString,
                response_deserializer=PartiiService__pb2.EmotionResult.FromString,
                )
        self.LiveSpeakerDiarization = channel.stream_stream(
                '/partii.Transcription/LiveSpeakerDiarization',
                request_serializer=PartiiService__pb2.AudioData.SerializeToString,
                response_deserializer=PartiiService__pb2.SpeakerResult.FromString,
                )
        self.CalibrateVad = channel.stream_unary(
                '/partii.Transcription/CalibrateVad',
                request_serializer=PartiiService__pb2.AudioData.SerializeToString,
                response_deserializer=PartiiService__pb2.CalibrateVadResult.FromString,
                )
        self.GetAvailable = channel.unary_unary(
                '/partii.Transcription/GetAvailable',
                request_serializer=PartiiService__pb2.EmptyMsg.SerializeToString,
                response_deserializer=PartiiService__pb2.AvailableConnection.FromString,
                )
        self.GetBuildNumber = channel.unary_unary(
                '/partii.Transcription/GetBuildNumber',
                request_serializer=PartiiService__pb2.EmptyMsg.SerializeToString,
                response_deserializer=PartiiService__pb2.BuildNumber.FromString,
                )


class TranscriptionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWordID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WakeWord(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WakeWordAndLiveTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SingleTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveEmotion(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveSpeakerDiarization(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateVad(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuildNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWordID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWordID,
                    request_deserializer=PartiiService__pb2.Word.FromString,
                    response_serializer=PartiiService__pb2.WordResult.SerializeToString,
            ),
            'WakeWord': grpc.stream_stream_rpc_method_handler(
                    servicer.WakeWord,
                    request_deserializer=PartiiService__pb2.AudioData.FromString,
                    response_serializer=PartiiService__pb2.WakeWordResult.SerializeToString,
            ),
            'WakeWordAndLiveTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.WakeWordAndLiveTranscribe,
                    request_deserializer=PartiiService__pb2.AudioData.FromString,
                    response_serializer=PartiiService__pb2.WakeWordAndTranscriptionResult.SerializeToString,
            ),
            'SingleTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.SingleTranscribe,
                    request_deserializer=PartiiService__pb2.AudioData.FromString,
                    response_serializer=PartiiService__pb2.TranscriptionResult.SerializeToString,
            ),
            'LiveTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.LiveTranscribe,
                    request_deserializer=PartiiService__pb2.AudioData.FromString,
                    response_serializer=PartiiService__pb2.TranscriptionResult.SerializeToString,
            ),
            'FileTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.FileTranscribe,
                    request_deserializer=PartiiService__pb2.AudioData.FromString,
                    response_serializer=PartiiService__pb2.TranscriptionResult.SerializeToString,
            ),
            'LiveEmotion': grpc.stream_stream_rpc_method_handler(
                    servicer.LiveEmotion,
                    request_deserializer=PartiiService__pb2.AudioData.FromString,
                    response_serializer=PartiiService__pb2.EmotionResult.SerializeToString,
            ),
            'LiveSpeakerDiarization': grpc.stream_stream_rpc_method_handler(
                    servicer.LiveSpeakerDiarization,
                    request_deserializer=PartiiService__pb2.AudioData.FromString,
                    response_serializer=PartiiService__pb2.SpeakerResult.SerializeToString,
            ),
            'CalibrateVad': grpc.stream_unary_rpc_method_handler(
                    servicer.CalibrateVad,
                    request_deserializer=PartiiService__pb2.AudioData.FromString,
                    response_serializer=PartiiService__pb2.CalibrateVadResult.SerializeToString,
            ),
            'GetAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailable,
                    request_deserializer=PartiiService__pb2.EmptyMsg.FromString,
                    response_serializer=PartiiService__pb2.AvailableConnection.SerializeToString,
            ),
            'GetBuildNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuildNumber,
                    request_deserializer=PartiiService__pb2.EmptyMsg.FromString,
                    response_serializer=PartiiService__pb2.BuildNumber.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'partii.Transcription', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transcription(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWordID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/partii.Transcription/GetWordID',
            PartiiService__pb2.Word.SerializeToString,
            PartiiService__pb2.WordResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WakeWord(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/partii.Transcription/WakeWord',
            PartiiService__pb2.AudioData.SerializeToString,
            PartiiService__pb2.WakeWordResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WakeWordAndLiveTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/partii.Transcription/WakeWordAndLiveTranscribe',
            PartiiService__pb2.AudioData.SerializeToString,
            PartiiService__pb2.WakeWordAndTranscriptionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SingleTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/partii.Transcription/SingleTranscribe',
            PartiiService__pb2.AudioData.SerializeToString,
            PartiiService__pb2.TranscriptionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LiveTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/partii.Transcription/LiveTranscribe',
            PartiiService__pb2.AudioData.SerializeToString,
            PartiiService__pb2.TranscriptionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/partii.Transcription/FileTranscribe',
            PartiiService__pb2.AudioData.SerializeToString,
            PartiiService__pb2.TranscriptionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LiveEmotion(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/partii.Transcription/LiveEmotion',
            PartiiService__pb2.AudioData.SerializeToString,
            PartiiService__pb2.EmotionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LiveSpeakerDiarization(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/partii.Transcription/LiveSpeakerDiarization',
            PartiiService__pb2.AudioData.SerializeToString,
            PartiiService__pb2.SpeakerResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalibrateVad(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/partii.Transcription/CalibrateVad',
            PartiiService__pb2.AudioData.SerializeToString,
            PartiiService__pb2.CalibrateVadResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/partii.Transcription/GetAvailable',
            PartiiService__pb2.EmptyMsg.SerializeToString,
            PartiiService__pb2.AvailableConnection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBuildNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/partii.Transcription/GetBuildNumber',
            PartiiService__pb2.EmptyMsg.SerializeToString,
            PartiiService__pb2.BuildNumber.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
