// Generated by gencpp from file nectec/DectectionRLRequest.msg
// DO NOT EDIT!


#ifndef NECTEC_MESSAGE_DECTECTIONRLREQUEST_H
#define NECTEC_MESSAGE_DECTECTIONRLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nectec
{
template <class ContainerAllocator>
struct DectectionRLRequest_
{
  typedef DectectionRLRequest_<ContainerAllocator> Type;

  DectectionRLRequest_()
    : timeout(0.0)  {
    }
  DectectionRLRequest_(const ContainerAllocator& _alloc)
    : timeout(0.0)  {
  (void)_alloc;
    }



   typedef float _timeout_type;
  _timeout_type timeout;





  typedef boost::shared_ptr< ::nectec::DectectionRLRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nectec::DectectionRLRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DectectionRLRequest_

typedef ::nectec::DectectionRLRequest_<std::allocator<void> > DectectionRLRequest;

typedef boost::shared_ptr< ::nectec::DectectionRLRequest > DectectionRLRequestPtr;
typedef boost::shared_ptr< ::nectec::DectectionRLRequest const> DectectionRLRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nectec::DectectionRLRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nectec::DectectionRLRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nectec::DectectionRLRequest_<ContainerAllocator1> & lhs, const ::nectec::DectectionRLRequest_<ContainerAllocator2> & rhs)
{
  return lhs.timeout == rhs.timeout;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nectec::DectectionRLRequest_<ContainerAllocator1> & lhs, const ::nectec::DectectionRLRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nectec

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nectec::DectectionRLRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nectec::DectectionRLRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nectec::DectectionRLRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nectec::DectectionRLRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nectec::DectectionRLRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nectec::DectectionRLRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nectec::DectectionRLRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e929ace7fd80dc265b8b96078f41e82";
  }

  static const char* value(const ::nectec::DectectionRLRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e929ace7fd80dc2ULL;
  static const uint64_t static_value2 = 0x65b8b96078f41e82ULL;
};

template<class ContainerAllocator>
struct DataType< ::nectec::DectectionRLRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nectec/DectectionRLRequest";
  }

  static const char* value(const ::nectec::DectectionRLRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nectec::DectectionRLRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 timeout\n"
;
  }

  static const char* value(const ::nectec::DectectionRLRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nectec::DectectionRLRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DectectionRLRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nectec::DectectionRLRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nectec::DectectionRLRequest_<ContainerAllocator>& v)
  {
    s << indent << "timeout: ";
    Printer<float>::stream(s, indent + "  ", v.timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NECTEC_MESSAGE_DECTECTIONRLREQUEST_H
