// Generated by gencpp from file nectec/DectectionRL.msg
// DO NOT EDIT!


#ifndef NECTEC_MESSAGE_DECTECTIONRL_H
#define NECTEC_MESSAGE_DECTECTIONRL_H

#include <ros/service_traits.h>


#include <nectec/DectectionRLRequest.h>
#include <nectec/DectectionRLResponse.h>


namespace nectec
{

struct DectectionRL
{

typedef DectectionRLRequest Request;
typedef DectectionRLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DectectionRL
} // namespace nectec


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nectec::DectectionRL > {
  static const char* value()
  {
    return "bf270a3091a6f4c4532e2ae7f6534df5";
  }

  static const char* value(const ::nectec::DectectionRL&) { return value(); }
};

template<>
struct DataType< ::nectec::DectectionRL > {
  static const char* value()
  {
    return "nectec/DectectionRL";
  }

  static const char* value(const ::nectec::DectectionRL&) { return value(); }
};


// service_traits::MD5Sum< ::nectec::DectectionRLRequest> should match
// service_traits::MD5Sum< ::nectec::DectectionRL >
template<>
struct MD5Sum< ::nectec::DectectionRLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nectec::DectectionRL >::value();
  }
  static const char* value(const ::nectec::DectectionRLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nectec::DectectionRLRequest> should match
// service_traits::DataType< ::nectec::DectectionRL >
template<>
struct DataType< ::nectec::DectectionRLRequest>
{
  static const char* value()
  {
    return DataType< ::nectec::DectectionRL >::value();
  }
  static const char* value(const ::nectec::DectectionRLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nectec::DectectionRLResponse> should match
// service_traits::MD5Sum< ::nectec::DectectionRL >
template<>
struct MD5Sum< ::nectec::DectectionRLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nectec::DectectionRL >::value();
  }
  static const char* value(const ::nectec::DectectionRLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nectec::DectectionRLResponse> should match
// service_traits::DataType< ::nectec::DectectionRL >
template<>
struct DataType< ::nectec::DectectionRLResponse>
{
  static const char* value()
  {
    return DataType< ::nectec::DectectionRL >::value();
  }
  static const char* value(const ::nectec::DectectionRLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NECTEC_MESSAGE_DECTECTIONRL_H
